baseURL: https://ouedraogoassami1.netlify.app
languageCode: en-us
title: portofolio website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Hello dear all welcome to my portofolio website.
    title: Hi, Welcome
  blog: {}
  contact:
    address:
      - city: Koudougou
        country: Burkina Faso
        street: 201
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ouedraogoassami03@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 54 25 95 28 / 63 11 43 95
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sami Corporate
    enable: yes
    quicklinks:
      - alt: Assami Ouedraogo
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/Ouedrao13144028
      - icon: fa-facebook
        label: Facebook
        url: https://m.facebook.com/home.php?_rdr
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/assami232/
      - icon: fa-github
        label: GitHub
        url: https://www.AssamiOuedraogo.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/assami-ouedraogo-486b27189
  image: ''
  name: Ouedraogo Assami
  subtitle:
  title: Profil
  tiles:
    enable: yes
    showcase:
      - image: experiences.jpg
        subtitle:  
        title: Professsional experiences 
        url: blogs/experiences
      - image: langages.jpg
        subtitle:
        title: Languages
        url: blogs/languages
      - image: educations.jpg
        subtitle: 
        title: Educations
        url: blogs/educations
      - image: skills.jpg
        subtitle:
        title: Skills
        url: blogs/skills
      - image: loisirs.jpg
        subtitle:
        title: Loisirs
        url: blogs/loisirs
      - image: motivations.jpg
        subtitle: 
        title: Motivation
        url: blogs/motivation
