baseURL: https://ouedraogoassami1.netlify.app
languageCode: en-us
title: My professsional presentation
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Hello dear all welcome to my portofolio website.
    title: Hi, my name is Assami Ouedraogo
  blog: {}
  contact:
    address:
      - city: Koudougou
        country: Burkina Faso
        street: 201
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ouedraogoassami03@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 54 25 95 28 / 63 11 43 95
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sami Corporate
    enable: yes
    quicklinks:
      - alt: Assami Ouedraogo
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/Ouedrao13144028
      - icon: fa-facebook
        label: Facebook
        url: https://m.facebook.com/home.php?_rdr
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/assami232/
      - icon: fa-github
        label: GitHub
        url: https://www.AssamiOuedraogo.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/assami-ouedraogo-486b27189
  image: ''
  name: Ouedraogo Assami
  navigation:
    button1:
      - name: Learn more
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Assami Corporate
    title: Profil
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle:  
        title: Professsional experiences 
        url: blogs/experiences
      - image: pic02.jpg
        subtitle:
        title: Languages
        url: blogs/languages
      - image: pic03.jpg
        subtitle: 
        title: Educations
        url: blogs/educations
      - image: pic04.jpg
        subtitle:
        title: Skills
        url: blogs/skills
      - image: pic05.jpg
        subtitle:
        title: Loisirs
        url: blogs/loisirs
      - image: pic06.pg
        subtitle: 
        title: Motivation
        url: blogs/motivation
  #two:
   # buttonText: Get Started
    #enable: yes
    #subtitle: "Hello World i am Ouedraogo Assami.I am a software and web developer.
    #i studied computer science at Burkina Institute of technology.i a real pleasure for me 
    #to be part to the developer family in the world.So like debate,travel and read."
    #title: About me
    #url: blogs


    
    
