baseURL: https://ouedraogoassami1.netlify.app
languageCode: en-us
title: CV
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
     this is the way for me to introduce my self by using a website
    title: Hi, my name is Assami Ouedraogo
  blog: {}
  contact:
    address:
      - city: Koudougou
        country: Burkina Faso
        street: 201
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ouedraogoassami03@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 54 25 95 28 / 63 11 43 95
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sami Corporate
    enable: yes
    quicklinks:
      - alt: Assami Ouedraogo
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.Assami Ouedraogo.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.AssamiOuedraogo.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/assami-ouedraogo-486b27189
  image: ''
  name: Ouedraogo Assami
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: I am passionate by coding  
        title: Programmer
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: i am excited about how to design everything
        title: Designer
        url: i am excited about how to design everything
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Web marketer
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hello World i am Ouedraogo Assami.I am a software and web developer.
    i studied computer science at Burkina Institute of technology.i a real pleasure for me 
    to be part to the developer family in the world.So like debate,travel and read."
    title: About me
    url: blogs
